### ISSUE TITLE
Individual perk popularity rankings not appearing

### ISSUE THREAD

**Issue by SquiIIiam** [leonardoneumann/DimPlus#19]
I'm no longer able to see the perk popularity ranking number that would appear on each perk bubble on the weapon inspection window. Tested in DIM Beta and main release.
![image](https://github.com/leonardoneumann/DimPlus/assets/41926008/763ef9cf-8490-4144-834d-3a2e3a198e7d)

**Comment by leonardoneumann** [comment]
fixed on version 0.9, thanks for reporting !

**Comment by SquiIIiam** [comment]
Thanks!

**Comment by SquiIIiam** [comment]
Hey with 0.9 I'm seeing it work on some of my guns but it still does not show the popularity rankings on most of my items. At a glance it seems that it's working on all my crafted weapons, but not random rolls.
